language: python

python:
    - 2.7

before_install:
    - sudo apt-get update
    - sudo apt-get install python-opencv

install:
    - "xargs -a requirements.txt -n 1 pip install || :"

script:
    - make lint
    - make cover

after_success:
    - coveralls
